# Generated by Django 3.2 on 2022-05-24 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Localidad')),
                ('cp', models.IntegerField(verbose_name='Código postal')),
            ],
            options={
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='N° de documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('num_cuit', models.IntegerField(blank=True, max_length=20, null=True, verbose_name='N° de cuil/cuit')),
                ('fecha_nac', models.DateField(default=datetime.datetime, verbose_name='Fecha de nacimiento')),
                ('telefono', models.IntegerField(max_length=50, verbose_name='N° de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='odontologia.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
