# Generated by Django 3.2.7 on 2021-10-09 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('I', 'Miercoles'), ('J', 'Juves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], default='L', max_length=1, verbose_name='Dia de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('receta', models.CharField(max_length=500)),
                ('obs', models.CharField(max_length=500, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('web', models.URLField(verbose_name='Sitio Web')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Alta Médica')),
                ('tipo_sangre', models.CharField(max_length=10, verbose_name='Tipo de Sangre')),
                ('antecedentes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('nombreOS', models.CharField(max_length=100, verbose_name='Nombre - Obra Social')),
                ('cuit', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('numeroHC', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Hoja Clínica')),
                ('numeroOS', models.CharField(max_length=50, verbose_name='Número de la Obra Social')),
                ('titularOS', models.BooleanField(default=False, verbose_name='¿Es titular de la obra social?')),
                ('obrasocial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obrasocial', to='odontologia.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nº de documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido/s')),
                ('num_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº de CUIT/CUIL')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='odontologia.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Pieza Dental')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=200)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesional_persona', to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña de Usuario')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_persona', to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorio', models.CharField(max_length=5)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de la consulta')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_establecimiento', to='odontologia.establecimiento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_medico', to='odontologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_paciente', to='odontologia.paciente')),
            ],
            options={
                'ordering': ['paciente', 'medico', 'consultorio', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Prestación')),
                ('descripcion', models.CharField(max_length=300)),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieza_dental_prestacion', to='odontologia.piezadental')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_persona', to='odontologia.persona'),
        ),
        migrations.CreateModel(
            name='FichaMedicaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FichaMedica_Consulta_Consulta', to='odontologia.consulta')),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FichaMedica_Consulta_FichaMedica', to='odontologia.fichamedica')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_paciente', to='odontologia.paciente'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimiento_localidad', to='odontologia.localidad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medico_consulta', to='odontologia.profesional'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_consulta', to='odontologia.prestacion'),
        ),
        migrations.CreateModel(
            name='CalendarioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_hora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_dia_hora', to='odontologia.calendario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Calendario_turno_profesional', to='odontologia.profesional')),
            ],
        ),
    ]
