# Generated by Django 3.2 on 2022-07-23 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1, verbose_name='Día de la semana')),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_cuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° de cuil/cuit'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_doc',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='N° de documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(verbose_name='N° de telefono'),
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontologia.persona')),
            ],
        ),
    ]
